version: '3.0'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/flask-api
    env_file:
      - castlabs-variables.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/status || exit 1"]