version: '3.8'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/flask-api
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/status || exit 1"]
    restart: on-failure
    secrets:
      - jwt_token
      - flask_secret
secrets:
  jwt_token:
    file: ./secrets/jwt_token.txt
  flask_secret:
    file: ./secrets/flask_secret.txt